name: generate snake

on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * *"
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate snake svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: deploy snake to output branch
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: output
          folder: dist
          clean: false
